[package]
name = "hyper"
version = "0.1.0"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
edition = "2018"

[dependencies]
hyper = "0.13.1"
tokio = { version = "1.8", features = ["full"] }
