[package]
name = "hyper"
version = "0.1.0"
authors = ["Roberto Huertas <roberto.huertas@outlook.com>"]
edition = "2018"

[dependencies]
hyper = "0.14.12"
tokio = { version = "0.2", features = ["full"] }
